### PR TITLE
Switch to using rollup instead of esperanto.

### PR DESCRIPTION
**Pull request by tafsiri**
This switches our bundler to use rollup instead of esperanto. Reasons for this include that the author of the both (its the same person) recommends it and has deprecated esperanto. Advantages include:

 - Better error messages: e.g. Rather than the cryptic thing it did before, this will be produced if it can't parse the code
```
Running "rollup" task
Error builing library
 {
    "pos": 1252,
    "loc": {
        "line": 57,
        "column": 0
    },
    "raisedAt": 1254,
    "code": "PARSE_ERROR",
    "file": "/Users/yannick/Bocoup/Projects/moebio/moebio_framework/src/dataTypes/structures/elements/Node.js"
}
```

 - UMD Build: This is not because of rollup, but in switching i'm also switching to making a UMD bundle instead of an AMD one. Basically nothing changes except for the fact that we also support AMD and CJS in addition to the ```mo``` global object. Win win win.

 - No more need for Loader.js: The above point also means i don't need loader js anymore. Nor the task I had to realign the sourcemap. Its all generated in one step.

__Other Changes__

In this PR you will notice a change to the way inheritance is done. Basically going from 

```
Relation.prototype = new Node();
```
to
```
Relation.prototype = Object.create(Node.prototype);
```

This is an improvement and solves some issues around some brittleness we experienced recently, that cause issues in curcular dependencies as well as forward references in some cases (in the built file). Basically with the former because the constructor for a ```Node``` is being called at parse time/initial read time. And in fact was being called before the full class definition has been read for things referred to in in that constructor (in this example NodeList). The latter method sets up the prototype chain, but we defer calling the constructor of the super class until we actually are in the constructor for the sub class. The latter is also better as you can call the super constructor with proper arguments. 

Changing this one line was required to make this build work, but in general i propose we change __all of them__ to follow this pattern (with calling the super constructor being optional in cases where it has no effect, e.g. list, numberlist etc), as it will make the build less brittle (as is it is possible to create dependency chains that just cannot load at runtime.

### CODE REVIEW

**Comment by tafsiri** [comment]
Note: once reviewed I would remove the old esperanto related code before final merge. But in this branch grunt build, grunt watch and grunt build-fast use rollup.

**Comment by tafsiri** [comment]
More on inheritance and object.create

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create

**Comment by vlandham** [comment]
+1

**Comment by protozoo** [comment]
+1

**Pull request merged**
