### PR TITLE
Table - constructor updated revA ref #231

### PR DESCRIPTION
**Pull request by Javingka**
@Jeff-Clark @moebio.

Here an example project where I tested the changes.  /JavierC/tests/newTable

One thing to note, that I made as a proposal, is that, when you create a Table using just one String as argument, it is used as the name of the Table. And if you use several String arguments, the Table is created with many Lists as Strings, using them as the names for those Lists. 
I am not sure about this, so in yours experiences you can tell me if this does or doesn't make sense.

Thanks, 

(I see this branch is not updated with the master, so after yours comments I will do a new pull-request or push)

### CODE REVIEW

**Comment by Jeff-Clark** [comment]
Found one bug. Inside loop on line 94 of Table.js you are using index [0] rather than the loop index [i]. In your test project this shows up in T_3_1 where all the lists are called ListA_Name.

    // STRING check if the argument is a string, If so create a List using the string as name
    else if ( typeof argmnts[0] == 'string' ) {
      var L = new List();
      L.name = argmnts[0];
      _args[i] = L;

Otherwise works as expected for me with the exception of the idea @Javingka mentioned above.
I think Table('w1') should create a single list with name 'w1' just as Table('w1','w2','w3') makes 3 named lists.

**Comment by Javingka** [comment]
oh!, yes I see, thanks!.

And, I like your idea @Jeff-Clark . It seems more consistent a String used as parameter is always a name for a List, no matter if is only one or more, (or even if is mixed with other type of parameters?).

So, right now, considering this Table creation behaviour, this are some examples: 

```
var a = new Array(3);         //  -> [  ,  ,  ]
var l = new List(3);          //  -> [ 3 ]
var s = new StringList('w');  //  -> [ 'w' ]
var nT = new NumberTable(3);  //  ->  [ [] , [] , [] ] 
var T = new Table(3);         // ->  [ [] , [] , [] ]  
var Ts = new Table('w');      // ->  [ [] ]  // 'w' as a name

var a   = new Array(3,3,3);              //  -> [ 3 , 3 , 3 ]
var l    = new List(3,3,3);              // ->  [ 3 , 3 , 3 ]
var s   = new StringList('w','w','w');   //  -> [ 'w' , 'w' , 'w' ]
var nT_a = new NumberTable([3,3,3]);      // ->  [ [ 3 , 3 , 3 ] ] 
var nT = new NumberTable(3,3,3);         // ->  [ [ 3 , 3 , 3 ] ] 
var T   = new Table(3,3,3);              // ->  [ [3] , [3] , [3] ]  
var Ts = new Table('w','w','w');         // ->  [ [] , [] , [] ]  // 'w' as a name
var T   = new Table(3,3,'w');            // ->  [ [3] , [3] , [] ]  // 'w' as a name
```

Now, considering this situation, should we change the output of new NumberTable(3,3,3);  from  [ [ 3 , 3 , 3 ] ]  to  [ [3] , [3] , [3] ] ??  Being a new Table, shouldn't treat its arguments as new Lists (as in new Table(3,3,3) )?

**Comment by Jeff-Clark** [comment]
Yes, I think that is reasonable to change NumberTable(3,3,3) to give [ [3] , [3] , [3] ] to be consistent with Table.
We should be careful about changing the behaviour because existing code might depend on it working the way it was before. I think, however, that you just did the improvements to NumberTable back in February? Likely there is no code depending on the old behaviour. I scanned moebio_framework.js and everything under modular_platform and didn't see anything like _new NumberTable(dd,dd)_ so I think we are good to make this change also.

**Comment by Javingka** [comment]
Request re-opened here: https://github.com/moebiolabs/moebio_framework/pull/234

**Pull request closed without merging**
