### PR TITLE
Add TableOperators.filterTable

### PR DESCRIPTION
**Pull request by Jeff-Clark**
This addresses the user request in https://github.com/moebiolabs/modular_platform/issues/93 by providing a quick operator to filter the rows in a table.

ping @moebio 
One aspect of the solution I'm not sure about is the default '=c' operator. It matches numbers exactly (using ==) but matches strings using the 'contains' operator - substring matching. It supports what I think people will usually want to do but is complex.

It might make sense to get rid of it and use either '==' as the default or use 'contains' as the default. The 'contains' operator has the property that it treats numbers as string literals so 11 would match 2117 for example. That's why I thought it might be better to have the hybrid '=c' .

The workspace http://lichen-stg.moebio.com/modular_platform/LICHEN/#/jeff/test/filterTable might be useful for testing.

### CODE REVIEW

**Comment by moebio** [comment]
I propose a change in name, a one that explains the kind of filtering the functions does

(there are already some filter operators for Table:

getSubTableByElementOnList
getSubTableByElementsOnList
table.getRows
table.sliceRows
)

And there's this filter operator for lists:

/**
 * Filters a list by the values of a property on its elements, and a type of comparison (equal by default).
 *
 * @param  {String} propertyName name of property
 * @param  {Object} propertyValue object (for equal or different comparison) or number or date (for equal, different, greater, lesser)
 * @param  {String} comparison equal (default), different, greater, lesser
 * @return {List} filtered list
 * tags:filter
 */
List.prototype.getFilteredByPropertyValue = function(propertyName, propertyValue, comparison)

Your new Table filter and this List operator should have consistent names and behavior (specially the comparator inlet values)… and actually the Table operator should use the list operator.

Please feel free to modify both functions in order to achieve consistency.

**Comment by moebio** [comment]
@Jeff-Clark please see previous comments

**Comment by Jeff-Clark** [comment]
ping @moebio 
This is kind of messy.
- my new function is most like a generalized version of TableOperators.getSubTableByElementOnList where you can use other comparison operators besides equality and you can check all the lists rather than just one. The name itself is not well suited to a generalized version.
- List.prototype.getFilteredByPropertyValue checks against property values, not element values and so is quite different again. It doesn't make sense to change it to match the new function.
- There exists a List.prototype.getFilteredByValue which is more analogous to my new function. However, the code for it is a duplicate of List.prototype.getFilteredByPropertyValue. It looks like it was copied and never changed to actually do what it claims to do. I can find no reference to it being used anywhere currently.

I propose to:
1. name my new function TableOperators.getFilteredByValue
2. remove the current broken (and likely unused) List.prototype.getFilteredByValue
3. add a new ListOperators.getFilteredByValue that has same inlets as TableOperators.getFilteredByValue (except for nList which is not relevant)

It is not possible to build TableOperators.getFilteredByValue using ListOperators.getFilteredByValue and have it perform efficiently. It is however, easy and fast to do the reverse by wrapping a single list in a table. This has the advantage of reusing the guts of the code by referencing it rather than copying and pasting it.

**Comment by Jeff-Clark** [comment]
I have implemented with the exception of part 3 above.

For part 3 adding the ListOperators.getFilteredByValue broke the framework in ways I don't understand. I had to add an import for TableOperators inside of ListOperators to implement that function. When the framework was built with that import present it crashed Lichen with errors. My best guess is that our infrastructure to handle ES6 modules does not always handle cyclic dependency properly. With my addition we had ListOperators importing TableOperators and already we have the reverse.

I vaguely recall @tafsiri and others hitting this problem in another case and maybe resolving it by changing order of import statements. Perhaps they can shed some light on the problem.

**Comment by moebio** [comment]
+1 (I understand you managed to make it work without breaking)

Yes, kind of a mess… but I think now it's good, it offers several different perspectives for filtering… at some point, we will be building a lich project that exemplifies all the major approaches and it will be clearer what are the similarities, differences, complementarities.

**Pull request merged**
