### PR TITLE
Improve categorical colors

### PR DESCRIPTION
**Pull request by Jeff-Clark**
To address issue #201 raised by @moebio.

Inside ColorListGenerators the method createDefaultCategoricalColorList uses createCategoricalColors to construct the list. It used to take a pseudorandom(but deterministic) sample of nColors from ColorScales.temperature. The result (labeled Old below) had lots of greenish hues and some very dark colors.
screen shot 2015-09-16 at 10 05 42 am

It is very difficult to algorithmically generate pleasing palettes of many distinct colors. I tried an approach using the full spectrum and some enhancements to the evolutionary algorithm. This option is available with mode 4 in createCategoricalColors but I wasn't happy with the results.

Instead I chose to use a fixed palette. Our existing hardcoded palette isn't bad but of the first 4 colors 2 are shades of orange and 2 shades of blue.
screen shot 2015-09-15 at 8 23 22 pm

I hand-constructed a new palette for our hardcoded colors and use it in the createDefaultCategoricalColorList method. It has 20 colors and the code uses darker versions of the colors if more than 20 are required.
screen shot 2015-09-16 at 10 16 52 am

- The project http://lichen-stg.moebio.com/modular_platform/LICHEN/#/jeff/colorListShow might be useful for testing (saved locally so it uses appropriate code)

### CODE REVIEW

**Comment by Jeff-Clark** [comment]
As part of this work I added ColorListGenerators.createColorListSpectrum. It is similar in some ways to ColorScales.temperature but uses the full spectrum and doesn't use white and black. It is not suited for showing magnitude because the colors on the 2 ends of the spectrum are almost the same. It's made by passing through all hue values and hue 0 == hue 360. For this reason it is implemented as a ColorListGenerator rather than a ColorScales.
screen shot 2015-09-16 at 10 42 22 am

**Comment by moebio** [comment]
@Jeff-Clark  I think all changes are good, except the proposal for changing the hardcoded basic palette. This palette is working very well in projects, in general. You proposal might be better in the sense it achieves more perceptual variability, but at the cost of modulating perceived luminosity. 0 and 1 in your platte, in particular, are vibrant colors; in any vis they will stand over the others, specially the ones in the bottom of the list.

You say "our existing hardcoded palette isn't bad but of the first 4 colors 2 are shades of orange and 2 shades of blue". Maybe you can try some minor manual adjustments to fix or at least balance a little bit this?

**Comment by Jeff-Clark** [comment]
Those are great comments regarding my proposed changes to the hard-coded palette. I'll look into reordering the existing palette entries and other minor adjustments.

**Comment by Jeff-Clark** [comment]
I went back to original hardcoded palette, changed a few of the really dark ones, and reordered a little. The result is:
screen shot 2015-09-23 at 8 58 50 am
There are still some shades of reds and browns that are too similar to each other but I think it a bit better than before. If you want reasonably consistent luminosity then we have no hope of having 22 easily distinguishable hues. The first 8 entries are pretty good for people with normal color vision.

**Comment by moebio** [comment]
+1

**Pull request merged**
