### PR TITLE
Updated NumberTable constructor and Table. ref #224

### PR DESCRIPTION
**Pull request by Javingka**
@moebio  
Here you can test it:
/JavierC/bugs/2DArray

As examples, these NumberTable creations are currently working:
````
  var a2d = [[1,1,1],[2,2,2],[3,3,3],[4,4,4]];
  var arr = [4,3,2,1,0]
  var nl = NumberList.fromArray([0,1,2,3,4,5,6,7,8,9]);

  var nT0 = new NumberTable();
  
  var nT_1_1 = new NumberTable(a2d);
  var nT_1_2 = new NumberTable(arr); // or [arr]
  var nT_1_3 = new NumberTable(nT_1_1);
  var nT_1_4 = new NumberTable(nl); // or [nl]
  var nT_1_5 = new NumberTable(5); // create a Table with five empty Lists
  var nT_1_6 = new NumberTable([5]); // create a Table with one List
  
  var nT_2_1 = new NumberTable([3,3,3],[4,4,4]); // or [[3,3,3],[4,4,4]]
  var nT_2_2 = new NumberTable(nl,nl); // or [nl,nl]
  var nT_2_3 = new NumberTable(arr,arr); // or [arr,arr]
  var nT_2_4 = new NumberTable(0,1,2,3); // or [0,1,2,3]
```

### CODE REVIEW

**Comment by moebio** [comment]
@Jeff-Clark please help us taking at look at this

**Comment by Jeff-Clark** [comment]
All my tests passed except for one. See project jeff/bug/2DArray
We have:
 var nl = NumberList.fromArray([0,1,2,3,4,5,6,7,8,9]);
 var nT_2_2 = new NumberTable(nl,nl);
 nl[0]=88;

and nT_2_2[0][0] == 88, should be 0. In this case we are not cloning the input numberLists but using them directly. So n1 and nT_2_2 are using same memory which we do not want for a constructor.

**Comment by Javingka** [comment]
Thanks @Jeff-Clark  I will look at this.

**Comment by moebio** [comment]
@Jeff-Clark can you please also take a quick look at the code? (I'd do the same later) It's important that this code is well written and efficient because: we'll be applying these procedures to the left data types; this is the first visible code in each data type; and finally because even if documentation will explain the instantiation options, it's not unlikely that developers will look into this code to see what are the options, so it has to be readable.

**Comment by Javingka** [comment]
thanks @moebio  and @Jeff-Clark ,  please give me a couple hours to clean the code ( I think I can improve it), fix the issue with the numberList input, make a new request, and then you take a look.

**Comment by Javingka** [comment]
Ok @Jeff-Clark  and @moebio, there is the commit I wanted to do. Thanks guys. I tried to write it in the more readable possible way.

**Comment by Jeff-Clark** [comment]
+1. Problem fixed and I also checked the code. It looks very good and well commented. The fetchArray is used recursively which can sometimes be a performance issue but I think here it usually goes only 1-2 levels deep so it won't be an problem.

**Comment by moebio** [comment]
@Javingka before merging, please add to the comments on top all the instantiation options info

**Pull request merged**
