### PR TITLE
Add methods in TableEncodings for a JSON-based format that preserves key attributes

### PR DESCRIPTION
**Pull request by Jeff-Clark**
A JSON representation of our Tables is useful for client/server processing since:
- JSON is portable across client/server boundary
- reasonably fast to parse (roughly 5-10 times faster than csv for example)
- supported across many languages
- we can encode our important attributes like name, type, column names and types

@moebio might want to check.

### CODE REVIEW

**Comment by moebio** [comment]
@Jeff-Clark please talk with @protozoo for he has already done related work. I believe is not the same but complementary with what you have done

I think he solved the conversion from ANY json to a table, whereas in your case you convert a json into a table only if it has the proper json format (basically the format resulting from your table to JSON operator).

This is Dani's operator: ObjectConversions.ObjectToTable

**Comment by Jeff-Clark** [comment]
We discussed the issue and we agreed that the related work @protozoo did was to handle generic objects without prior knowledge about their structure and it makes sense to have a specific function to handle my case.

In any case Dani's function uses stringify to build the JSON and which does not emit the Lichen specific details. It only serializes the 2D array for a Table.

Ideally, we should be able to convert any of our Lichen data objects into JSON and then recover all the important data from that JSON to reconstruct the object. The change I committed solves this for Table only. A more generic solution could be useful and Dani's ObjectConversions.ObjectToTable does not provide it.

**Comment by moebio** [comment]
Ok, now I understand much better. Your work here goes directly in the direction of being able to communicate with servers (perform operations there). 

Each type will have an official JSOn description, that can be coded and decoded, so operators on servers can receive them, treat them and eventually deliver and it will arrive as a JSON convertible to a mo type.

**Comment by Jeff-Clark** [comment]
Yes, exactly. Of course it can be used anywhere we need to transmit - not just between client and server.  I think there are cases when using postMessage between html frames that are loaded from different web domains where you can't pass the object directly.

**Comment by moebio** [comment]
Good. regarding the last comment, what you describe is what happens with external modules, and also with web-workers (they both work with postMessage). But in this case there's no need to convert to json string or json object, the only condition is that the delivered object doesn't contain functions. SO the serialization and de-serialization could be less transformative and costful (it could be for instance list into array, simply by cloning). For that other purpose I started this:  

ObjectOperators.serliazeObject

**Pull request merged**
